### ISSUE TITLE
ListView doesn't update in FutureBuilder when db has been updated in other pages

### ISSUE THREAD

**Issue by h4n0** [Rahiche/sqlite_demo#7]
I tried to implement my database with referring to your approach and I find it quite clean to separate all db related methods into one singleton class.

However, when I updated some values of my database on another page and returned back to home screen, it appeared the same (cached i guess) ListView like before. I put some log into the builder and it seems the home builds again, but future variable from the method of getting data from database is not called again after the db is updated. 

How do you see it? I checked on google and some suggest to use StreamBuilder instead. I would like to listen to your comments. thanks!

**Comment by Rahiche** [comment]
Hey @hanqo 
I just pushed a fix this [branch](https://github.com/Rahiche/sqlite_demo/tree/sqlite_demo_bloc) 
Sorry about the confusion this is a bit of an old outdated code

**Comment by h4n0** [comment]
Thank you for the quick reply @Rahiche  That is really helpful of looking into this branch! I think my issue should be solved with it.
